// APP STATE - DAY // LANGUAGE

// READ CORRECT FOLDER
// SHOW A RANDOM VOCABULARY IMAGE
// TICK TO ADD A SCORE METER WHEN DONE
// SHOW IMAGES DEPENDING ON THEIR SCORE -- HIGHER SCORE NOT AS IMPORTANT AS LOW
