            // TODO: HELLO, THIS IS YOUR SUPERIOR HERE. IN HONOR OF PARTY WORK REALLY HARD.
            //I BELIEVE IN YOU. IF ANYBODY CAN WORK THEMSELVES HALF TO DEATH FOR A CELEBRATION, ITS US
            //WEVE GOT THIS
            //RIBBIT
class Panel_Locations {

    constructor() {};

    // A LOCATION IF ANY FEATURE ATTACHED TO A PLANET THAT DOESNT FALL INTO THE OTHER CATEGORIES;
    // THE OTHER CATEGORIES ARE 
        // BAD
        // BUSINESS
        // PLACES OF INTEREEST
    
    // BAD LOCATIONS
        // LOCATIONS FOR TORTURE / IMPRISONMENT
        // USED BY THE BAD PEOPLE TO CAUSE HARM TO THE GOOD PEOPLE
            // TYPE
            // PLANET
            // NAME
            // BAD PEOPLE
            // NAMED GUARDS / STAFF
    // BUSINESSES
        // RETAIL OF SOME KIND
        // OWNED BY SOMEBODY OR AT LEAST RUN BY SOMEBODY FOR THE PURPOSES OF MAKING MONEY
            // SELL TYPE
            // BUSINESS TYPE
            // NAME
            // OWNER
            // ITEMS SOLD / PRODUCED

    // PLACES OF INTEREST
        // INTERESTING PLACES THAT MIGHT NOT HAVE A SPECIFIC USE FOR BUSINESS
        // MAY INCLUDE GEOLOGICAL FEATURES
        // THE KIND OF PLACE THAT YOU GO TO TO HAVE A LOOK BUT THAT DONT HAVE A REALLY DEFINED TERM ASSOCIATED
    // LOCATIONS
        // PLACES LIKE LABS AND SUCH THAT MDONT FIT IN TO OTHER GROUPS BUT ARE NONETHELESS IMPORTANT
        // IMPORTANT FOR CAREER AND HOUSING AND STUFF?

    // == INPUTS == //
    PANEL_INPUT_ITEM() {};
    PANEL_INPUT_TYPE() {};
    PANEL_INPUT_FLAVOUR() {};

}